name: improved_jenkins_client_func_tests
git: git://github.com/arangamani/improved_jenkins_client.git
ref: master
script:
 - bundle install
 - rake unit_tests
 - rake func_tests
 notification_email: kannan@rightscale.com
 notification_email_for_every_unstable: true
